- history_policy: &default_history_policy
    type: "memory" # "memory", "redis", "file", "mongodb" or your custom module name
    module_path: . # Path to module, Only needed if you are using a custom module
    time_to_live: 3600 # in seconds
    expiration_check_interval: 300 # in seconds
    history_policy: # History provider configs (Passed to the history type provider)
      max_turns: 40
      max_characters: 50000
      enforce_alternate_message_roles: true

- identity_config: &default_identity_config
    type: "passthru" # "passthru", "bamboohr", or your custom module name
    module_path: . # Path to module, Only needed if you are using a custom module
    configuration: {}

- gateway_config: &gateway_config
    gateway_id: {{GATEWAY_ID}}
    system_purpose: >
      The system is an AI Chatbot with agentic capabilities. It will use the agents available to provide information, reasoning and general assistance for the users in this system.      
        
    interaction_type: "interactive"

    identity:
      <<: *default_identity_config

    retain_history: true
    history_config: 
      <<: *default_history_policy
