
- rest_config: &rest_config
    listen_port: ${REST_API_SERVER_INPUT_PORT}
    endpoint: ${REST_API_SERVER_INPUT_ENDPOINT}
    rate_limit: ${REST_API_SERVER_INPUT_RATE_LIMIT}
    host: ${REST_API_SERVER_HOST}

- web_ui_config: &web_ui_config
    enabled: ${WEBUI_ENABLED}
    listen_port: ${WEBUI_PORT}
    host: ${WEBUI_HOST}
    response_api_url: ${WEBUI_RESPONSE_API_URL}
    solace_broker_rest_messaging_url: ${SOLACE_BROKER_REST_MESSAGING_URL}
    solace_agent_mesh_namespace: ${SOLACE_AGENT_MESH_NAMESPACE}
    solace_broker_basic_auth: ${SOLACE_BROKER_BASIC_AUTH}
    frontend_redirect_url: ${WEBUI_FRONTEND_REDIRECT_URL}
    frontend_server_url: ${WEBUI_FRONTEND_SERVER_URL}
    frontend_use_authorization: ${WEBUI_FRONTEND_USE_AUTHORIZATION}
    frontend_auth_login_url: ${WEBUI_FRONTEND_AUTH_LOGIN_URL}
    frontend_welcome_message: ${WEBUI_FRONTEND_WELCOME_MESSAGE}
    frontend_bot_name: ${WEBUI_FRONTEND_BOT_NAME}
    frontend_collect_feedback: ${WEBUI_FRONTEND_COLLECT_FEEDBACK}
    frontend_url: ${WEBUI_FRONTEND_URL}
    local_dev : ${WEBUI_LOCAL_DEV}

- response_format_prompt: &response_format_prompt >
    Use markdown formatting for text responses.
    FILE HANDLING REQUIREMENTS:
    - ALWAYS use <{{tag_prefix}}file> tags for files/images
    - NEVER use markdown image/link syntax or generic HTML tags for files
    